## **Intro to Pytorch**

PyTorch is an open-source machine learning library developed by Facebook's AI Research lab (FAIR). It is widely used for various machine learning tasks, including deep learning. PyTorch is known for its dynamic computational graph, which allows for more intuitive and flexible model development compared to static computational graphs used in some other frameworks.

Follow instructions in the link:
https://pytorch.org/tutorials/beginner/introyt/introyt1_tutorial.html



**Tensors**: Similar to TensorFlow, PyTorch uses tensors as the fundamental building blocks for numerical computations. Tensors are multi-dimensional arrays that can be used for various mathematical operations.

**Autograd**: PyTorch includes an automatic differentiation library called Autograd. This feature automatically computes gradients of tensors with respect to a given objective, which is essential for training machine learning models through techniques like backpropagation.

**Neural Network Module**: PyTorch provides a torch.nn module that simplifies the process of building and training neural networks. It includes pre-defined layers, loss functions, and optimization algorithms, making it easier for developers to construct and train models.

In [3]:
!pip install torch

     |████████████████████████████████| 766.7 MB 14 kB/s  eta 0:00:015     |██████████████████              | 430.8 MB 7.7 MB/s eta 0:00:44     |███████████████████▌            | 466.1 MB 8.7 MB/s eta 0:00:35
     |████████████████████████████████| 363.4 MB 2.2 MB/s eta 0:00:01     |███████████████████▋            | 223.0 MB 7.9 MB/s eta 0:00:18
     |████████████████████████████████| 211.5 MB 82 kB/s  eta 0:00:01
     |████████████████████████████████| 13.8 MB 3.6 MB/s eta 0:00:01
     |████████████████████████████████| 21.1 MB 4.7 MB/s eta 0:00:01
     |████████████████████████████████| 99 kB 5.7 MB/s eta 0:00:011
     |████████████████████████████████| 883 kB 6.4 MB/s eta 0:00:01
     |████████████████████████████████| 6.2 MB 6.2 MB/s eta 0:00:01
     |████████████████████████████████| 127.9 MB 258 kB/s eta 0:00:01
     |████████████████████████████████| 188.7 MB 3.6 MB/s eta 0:00:01
     |████████████████████████████████| 56.3 MB 6.2 MB/s eta 0:00:01
     |█████████████████████████

In [4]:
import torch
import numpy as np

## **Manipulating Tensors in PyTorch**

In [5]:
data = [3, 4]
x_data = torch.tensor(data)
x_data

tensor([3, 4])

Tensors can be created from NumPy arrays and vice versa. This allows for seamless integration with existing NumPy code and libraries.

In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

Using built-in functions:


In [7]:
# Tensor with random values between 0 and 1
rand_tensor = torch.rand(2, 3)

# Tensor with random values from a standard normal distribution
randn_tensor = torch.randn(2, 3)

# Tensor with all ones
ones_tensor = torch.ones(2, 3)

# Tensor with all zeros
zeros_tensor = torch.zeros(2, 3)

# Identity matrix
eye_tensor = torch.eye(3)

# Tensor with values from 0 to 9 (exclusive)
arange_tensor = torch.arange(10)

# Tensor with 10 values evenly spaced between 0 and 1
linspace_tensor = torch.linspace(0, 1, 10)

In [11]:
linspace_tensor.size()
linspace_tensor.dtype
linspace_tensor.device
linspace_tensor.layout

torch.strided

In [12]:
torch.cuda.is_available()

False

## **Tensor Attributes**

Understanding tensor attributes is crucial for effective manipulation:



*   Shape: A tuple of tensor dimensions, accessed using tensor. shape or` tensor.size()`. This determines the number of elements and their arrangement within the tensor.
*   Data type: The type of data stored in the tensor (e.g., torch.float32, torch.int64), accessed using `tensor.dtype`. This affects the precision and memory usage of the tensor.

*   Device: The device where the tensor is stored (CPU or GPU), accessed using `tensor.device`. This is important for utilizing GPU acceleration for faster computations.
*   Layout: The way the tensor is stored in memory (e.g., strided, sparse), accessed using `tensor.layout`. This can affect performance and memory usage.

## **Tensor Operations**

PyTorch supports a wide range of tensor operations:

Indexing and slicing: Accessing specific elements or sub-tensors using standard indexing and slicing techniques. This allows for extracting and manipulating parts of the tensor.



In [5]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Reshaping: Changing the shape of a tensor without altering its data using methods like `tensor.view()`, `tensor.reshape()`, and `tensor.transpose()`. This is often used to adapt tensors for different operations or layers in a neural network.

In [6]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


Concatenation: Joining tensors along a given dimension using `torch.cat()` or `torch.stack()`. This is useful for combining data or features.

In [17]:
# Create two tensors
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

# Concatenate along the existing axis (dim=0)
concatenated_tensor = torch.cat((tensor1, tensor2), dim=0)
concatenated_tensor1 = torch.cat((tensor1, tensor2))
stacked_tensor = torch.stack((tensor1, tensor2), dim=0)
stacked_tensor1 = torch.stack((tensor1, tensor2), dim=1)
print(concatenated_tensor)
print(concatenated_tensor1)
print(stacked_tensor)
print(stacked_tensor1)



tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


Mathematical operations: Performing arithmetic, linear algebra, matrix manipulation, and other mathematical operations on tensors. PyTorch provides a comprehensive set of functions for these operations.

In [18]:
# Matrix multiplication
y1 = stacked_tensor @ stacked_tensor.T
print(y1)
y2 = stacked_tensor.matmul(stacked_tensor.T)
print(y2)

# Element-wise multiplication
z1 = stacked_tensor * stacked_tensor
print(z1)
z2 = stacked_tensor.mul(stacked_tensor)
print(z2)

# Element-wise addition
stacked_tensor.add_(5)

tensor([[14, 32],
        [32, 77]])
tensor([[14, 32],
        [32, 77]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])


tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In-place operations: Operations that modify the tensor directly, denoted by an underscore postfix (e.g., `tensor.add_()`). These can be more memory-efficient but should be used with caution.

## **Using the Autograd Module**

The autograd module is PyTorch's automatic differentiation engine, crucial for training neural networks. This section covers gradients, Jacobians, Hessians, and computational graphs.

## **1. Gradients**

requires_grad: To compute gradients, set the `requires_grad=True` for a tensor. This enables tracking of operations on that tensor, creating a computational graph.

In [28]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

`.backward() `: Computes the gradients of a tensor with respect to its leaf nodes in the computational graph. This is the core of backpropagation.

In [33]:
y = x + 2
print(y)
z = y * y * 3
print(z)
out = z.mean()
print(out)
out.backward()
#print(out.backward())
print(x.grad)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)
tensor([[9., 9.],
        [9., 9.]])


`.grad`: Accesses the accumulated gradients for a tensor. This attribute stores the gradients computed during the `.backward()` call.

## **2. Jacobian Product**

For vector-valued functions, autograd computes the Jacobian product, which is the product of the Jacobian matrix and a given vector. This is more efficient than computing the full Jacobian matrix.

In [18]:

# Define a function
def func(x):
    return torch.stack([x[0]**2, x[1]**3])

# Create an input tensor with requires_grad=True
x = torch.tensor([1.0, 2.0], requires_grad=True)

# Compute the output of the function
y = func(x)

# Compute the Jacobian
jacobian = torch.zeros((2, 2))  # initialize a tensor to hold the Jacobian matrix
for i in range(2):
    y[i].backward(retain_graph=True)
    jacobian[i] = x.grad
    x.grad.zero_()  # zero the gradients for the next computation

print(jacobian)


tensor([[ 2.,  0.],
        [ 0., 12.]])


## **3. Hessians**

The Hessian matrix represents the second derivatives of a function, you can use the `torch.autograd.functional.hessian()` function to calculate it.

In [35]:
from torch.autograd.functional import hessian

def f(x):
    return x[0]**2 + x[1]**2

x = torch.tensor([1.0, 2.0], requires_grad=True)
hessian_matrix = hessian(f, x)
print(hessian_matrix)

tensor([[2., 0.],
        [0., 2.]])


In [37]:
def f(x):
    return x[0]**3 + x[1]**3 - 3*x[0] + 5*x[1]

x = torch.tensor([1.0, 0.0], requires_grad=True)
hessian_matrix = hessian(f, x)
print(hessian_matrix)

tensor([[6., 0.],
        [0., 0.]])


## **4. Computational Graph**

Autograd maintains a directed acyclic graph (DAG) representing the operations performed on tensors. This graph is dynamic and recreated after each `.backward()` call. Understanding this graph is crucial for debugging and optimizing your models.

## **5.  Disabling Gradient Tracking**

Gradient tracking can be disabled using `torch.no_grad()` to speed up computations when gradients are not needed, such as during inference or when evaluating a model.

In [20]:
with torch.no_grad():
    print((x ** 2).requires_grad)

False
